import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NEXTAUTH_URL: z.string().url(),
    NEXTAUTH_SECRET: z.string().min(32),
    MONGODB_URI: z.string().min(10),
    MONGODB_DB: z.string().min(1),
    OWNER_EMAIL: z.string().email().optional(),

    X_CLIENT_ID: z.string().optional(),
    X_CLIENT_SECRET: z.string().optional(),
    FACEBOOK_CLIENT_ID: z.string().optional(),
    FACEBOOK_CLIENT_SECRET: z.string().optional(),
    GOOGLE_CLIENT_ID: z.string().optional(),
    GOOGLE_CLIENT_SECRET: z.string().optional(),

    RESEND_API_KEY: z.string().optional(),
    MAIL_FROM: z.string().optional(),

    RATE_LIMIT_POINTS: z.string().optional(),
    RATE_LIMIT_DURATION_SEC: z.string().optional(),

    PLATFORM_FEE_BPS: z.string().optional(),
    PLATFORM_TREASURY_ADDRESS: z.string().optional(),
    X402_FACILITATOR_URL: z.string().optional(),
    SOLANA_RPC_URL: z.string().optional(),

    STRIPE_SECRET_KEY: z.string().optional(),
    STRIPE_WEBHOOK_SECRET: z.string().optional(),
    STRIPE_SUBSCRIPTION_PRICE_BASIC: z.string().optional(),
    STRIPE_SUBSCRIPTION_PRICE_PRO: z.string().optional(),
    STRIPE_SUBSCRIPTION_PRICE_ELITE: z.string().optional(),
    STRIPE_RGC_PACK_SMALL: z.string().optional(),
    STRIPE_RGC_PACK_MEDIUM: z.string().optional(),
    STRIPE_RGC_PACK_LARGE: z.string().optional(),
    STRIPE_PRICE_GOLD: z.string().optional(),
    STRIPE_PRICE_BUSINESS: z.string().optional(),
    STRIPE_PRICE_COINS: z.string().optional(),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().optional(),
    APP_URL: z.string().optional(),
  },
  client: { NEXT_PUBLIC_APP_NAME: z.string().min(1).default("ReelTokz") },
  runtimeEnv: {
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    MONGODB_URI: process.env.MONGODB_URI,
    MONGODB_DB: process.env.MONGODB_DB,
    OWNER_EMAIL: process.env.OWNER_EMAIL,
    X_CLIENT_ID: process.env.X_CLIENT_ID,
    X_CLIENT_SECRET: process.env.X_CLIENT_SECRET,
    FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
    FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    MAIL_FROM: process.env.MAIL_FROM,
    RATE_LIMIT_POINTS: process.env.RATE_LIMIT_POINTS,
    RATE_LIMIT_DURATION_SEC: process.env.RATE_LIMIT_DURATION_SEC,
    PLATFORM_FEE_BPS: process.env.PLATFORM_FEE_BPS,
    PLATFORM_TREASURY_ADDRESS: process.env.PLATFORM_TREASURY_ADDRESS,
    X402_FACILITATOR_URL: process.env.X402_FACILITATOR_URL,
    SOLANA_RPC_URL: process.env.SOLANA_RPC_URL,

    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    STRIPE_SUBSCRIPTION_PRICE_BASIC: process.env.STRIPE_SUBSCRIPTION_PRICE_BASIC,
    STRIPE_SUBSCRIPTION_PRICE_PRO: process.env.STRIPE_SUBSCRIPTION_PRICE_PRO,
    STRIPE_SUBSCRIPTION_PRICE_ELITE: process.env.STRIPE_SUBSCRIPTION_PRICE_ELITE,
    STRIPE_RGC_PACK_SMALL: process.env.STRIPE_RGC_PACK_SMALL,
    STRIPE_RGC_PACK_MEDIUM: process.env.STRIPE_RGC_PACK_MEDIUM,
    STRIPE_RGC_PACK_LARGE: process.env.STRIPE_RGC_PACK_LARGE,
    STRIPE_PRICE_GOLD: process.env.STRIPE_PRICE_GOLD,
    STRIPE_PRICE_BUSINESS: process.env.STRIPE_PRICE_BUSINESS,
    STRIPE_PRICE_COINS: process.env.STRIPE_PRICE_COINS,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    APP_URL: process.env.APP_URL,
  },
});
